### ISSUE TITLE
Add `renewedTo` field to `RPCLastestRevision` response

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/core#246]
In v2 a renter has no way of knowing whether a contract has been renewed when fetching a revision. So if a renter for some reason misses the fact that the contract was renewed (e.g. due to a crash mid-renewal), it would be nice of the host to tell the renter about it via a `renewedTo` field. Previously we used the max revision number for that but we don't have that anymore.

**Comment by ChrisSchinnerl** [comment]
@n8maninger I created this issue since it is something we discussed and after thinking about it I think it would be useful to have. Makes it easier to avoid failed interactions with hosts and also some of the contract maintenance checks.

**Comment by n8maninger** [comment]
Thinking about this more: instead of a `RenewedTo` field, maybe a "Resolved" field that includes the type? If `resp.Resolution == "renewal"`, you can calculate the renewed contract ID using the existing contract ID: `renewalID := fcid. V2RenewalID()`

**Comment by ChrisSchinnerl** [comment]
Sounds good to me. I don't feel strongly about either approach. The resolution might be a bit nicer since we only need to send another byte.

**Comment by lukechampine** [comment]
Perhaps make it `RPCContractStatus` and return something like `ForEachV2FileContractElement`?
```go
struct {
    Contract types.V2FileContractElement // latest on-chain revision
    Revision *types.V2FileContractRevision // latest off-chain revision, if it exists
    Resolution types.V2FileContractResolutionType // non-nil if contract has been resolved
}
```
